extends SceneTree
const Intro = preload("res://game/mode_intro.gd")
const Controller = preload("res://game/match_controller.gd")
const AudioPort = preload("res://src/audio/audio_port.gd")
const Audit = preload("res://src/audits/audit_base.gd")
func _initialize(): call_deferred("run")
func run():
	var audit = Audit.new("mode_intro")
	audit.check_true(Intro.enabled("career", {}), "career enabled by default")
	audit.check_true(not Intro.enabled("quick", {}), "quick unaffected")
	audit.check_true(not Intro.enabled("drill", {}), "training unaffected")
	audit.check_true(not Intro.enabled("career", {"intro_career": false}), "career can be disabled")
	audit.check_true(Intro.enabled("tournament", {"intro_career": false}), "settings independent")
	audit.check_true(Intro.should_celebrate("tournament", {"trophy": true}, true, {}), "tournament title celebrates")
	audit.check_true(not Intro.should_celebrate("tournament", {"trophy": false}, true, {}), "ordinary round does not celebrate")
	audit.check_true(Intro.should_celebrate("career", {"outcome": {"seasonWon": true}}, true, {}), "career title celebrates")
	audit.check_true(not Intro.should_celebrate("career", {"outcome": {"seasonWon": true}}, true, {"intro_career": false}), "career setting skips celebration")
	audit.check_eq(Intro.voice_for("career", 0, 0, "en"), Intro.CAREER_SEASON_VOICE, "new career season gets Bruno")
	audit.check_eq(Intro.voice_for("tournament", 0, 0, "en"), Intro.TOURNAMENT_OPENING_VOICE, "tournament opener gets Bruno")
	audit.check_eq(Intro.voice_for("tournament", 2, 0, "en"), Intro.TOURNAMENT_FINAL_VOICE, "tournament final gets Bruno")
	audit.check_true(Intro.voice_for("career", 0, 1, "en") == null, "later career match stays brief")
	audit.check_true(Intro.voice_for("tournament", 1, 0, "en") == null, "short semifinal stays silent")
	audit.check_true(Intro.voice_for("quick", 0, 0, "en") == null, "quick match stays silent")
	audit.check_eq(Intro.voice_for("career", 0, 0, "it"), Intro.CAREER_SEASON_VOICE, "Italian UI still gets Bruno's English intro")
	var camera = Camera3D.new()
	root.add_child(camera)
	camera.position = Vector3(0, 12, 15)
	var original = camera.transform
	var player = Node3D.new()
	root.add_child(player)
	player.position = Vector3(1, 0, 4)
	var player_original = player.transform
	var opponent = Node3D.new()
	root.add_child(opponent)
	opponent.position = Vector3(-1, 0, -4)
	var intro = Intro.new()
	root.add_child(intro)
	intro.begin(camera, "Test", "Calendar", 5.0, {"player": player, "opponent": opponent})
	audit.check_eq(intro._shots.size(), 4, "arena and actual athletes are staged")
	var controller = Controller.new()
	controller._mode_intro = intro
	audit.check_eq(controller.apply_frame({}, 10.0).steps, 0, "intro blocks simulation clock")
	intro.advance(1.0)
	audit.check_true(camera.transform != original, "camera presentation animates")
	var event = InputEventJoypadButton.new()
	event.pressed = true
	event.button_index = JOY_BUTTON_A
	intro.handle(event)
	intro.advance(0.0)
	audit.check_true(not intro.active, "controller skips")
	audit.check_eq(camera.transform, original, "camera restored exactly")
	audit.check_eq(player.transform, player_original, "athlete transform restored exactly")
	# In the playable scene MatchAudio builds the SFX bus before this overlay.
	var audio_port = AudioPort.new()
	root.add_child(audio_port)
	var voiced = Intro.new()
	root.add_child(voiced)
	voiced.begin(camera, "Season", "Calendar", 6.0, {"player": player}, "intro", {}, Intro.CAREER_SEASON_VOICE)
	audit.check_true(voiced.voice_player != null and voiced.voice_player.is_playing(), "Bruno plays during the introduction")
	audit.check_eq(voiced.voice_player.bus, "SFX", "intro respects SFX volume")
	voiced.request_skip()
	audit.check_true(not voiced.voice_player.is_playing(), "skip stops Bruno immediately")
	voiced.advance(0.0)
	audit.check_true(not voiced.active, "voiced intro closes after skip")
	var victory = Intro.new()
	root.add_child(victory)
	victory.begin(camera, "Champion", "Trophy", 4.0, {"player": player}, "victory")
	audit.check_eq(victory._shots.size(), 3, "victory shows arena, winner and trophy")
	audit.check_true(is_instance_valid(victory._trophy), "trophy is a real temporary 3D prop")
	victory.advance(5.0)
	audit.check_true(not victory.active, "victory completes without input")
	audit.check_eq(camera.transform, original, "victory restores gameplay camera")
	controller.free()
	audio_port.free()
	player.free()
	opponent.free()
	camera.free()
	await process_frame
	quit(audit.finish())
