#!/usr/bin/env python3
"""Arena kit image batch — resumable generator (arena-kit-v1).

Reads a prompt pack from ``tools/arena-kit/prompts/<arena>.json`` and produces
``art/arena-kits/<arena>/<slot>.png`` images that satisfy the Meshy-readiness
checklist (KIT-STANDARD §4), appending every attempt to the spend ledger
``art/arena-kits/image-spend.json`` and journaling progress to
``run/tmp/arena-kit/image-batch-journal.txt``.

Backend ladder (meshy recipe: image-prototyping.md §6, S25):
  1. ``hermes-tool``  — the Hermes image tool implementation. Imports the same
     provider module the in-session ``image_generate`` tool routes to
     (``plugins.image_gen.openai``: OpenAIImageGenProvider) inside the Hermes
     source tree, resolving the key through Hermes's own secret scope
     (``agent.secret_scope.get_secret``). No key is ever printed or handled here.
  2. ``jobs``         — when the provider is unavailable, emit the exact job
     payloads to ``run/tmp/arena-kit/jobs-pending.json`` so an in-session agent
     can run them with the native image tool and then ``--install`` each result.

Resumability: a slot whose delivered file already exists and passes the
programmatic check is skipped. ``--regen`` archives the rejected attempt under
``_rejected/`` and re-runs that one slot (policy: at most one regen per slot).

Commands:
  gen_assets.py --status                     ledger cap/remaining + worklist counts
  gen_assets.py --list                       pending slots per arena
  gen_assets.py --set-cap N --cap-reason R   raise/record the ledger cap
  gen_assets.py --run [--arena X] [--slots a,b] [--limit N]
  gen_assets.py --regen --arena X --slot S
  gen_assets.py --install CACHE --arena X --slot S   install an externally produced image
  gen_assets.py --verify [--arena X]         programmatic checklist over delivered files
  gen_assets.py --sheet --arena X            contact sheet for visual review
  gen_assets.py --manifest --arena X         write art/arena-kits/<arena>/MANIFEST.md
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import shutil
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PROMPTS = os.path.join(REPO, "tools", "arena-kit", "prompts")
KITS = os.path.join(REPO, "art", "arena-kits")
LEDGER = os.path.join(KITS, "image-spend.json")
JOURNAL = os.path.join(REPO, "run", "tmp", "arena-kit", "image-batch-journal.txt")
TMP = os.path.join(REPO, "run", "tmp", "arena-kit")
HERMES_SRC = os.path.expanduser("~/.hermes/hermes-agent")
HERMES_PROFILE_HOME = os.path.expanduser("~/.hermes/profiles/dev-work")

ARENAS = ["torii", "medina", "carioca", "aurora", "egeo"]
SLOTS = [
    "hero_landmark", "gate_portal", "light_source", "vegetation_cluster",
    "ground_dressing", "ornament_accent", "column_pillar", "railing_segment",
    "furniture", "signage_banner", "ground_texture",
]
# Slots the parent already delivered: never regenerated by this batch.
PARENT_DELIVERED = {("torii", "hero_landmark")}


# ------------------------------------------------------------------ small utils

def now() -> str:
    return datetime.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S%z")


def journal(line: str) -> None:
    os.makedirs(os.path.dirname(JOURNAL), exist_ok=True)
    with open(JOURNAL, "a") as fh:
        fh.write(f"[{now()}] {line}\n")


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def load_json(path: str) -> dict:
    with open(path) as fh:
        return json.load(fh)


def save_json(path: str, data: dict) -> None:
    tmp = path + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(data, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    os.replace(tmp, path)


def pack(arena: str) -> dict:
    return load_json(os.path.join(PROMPTS, f"{arena}.json"))


def delivered_path(arena: str, slot: str) -> str:
    return os.path.join(KITS, arena, f"{slot}.png")


# ------------------------------------------------------------------- checklist

def check_image(path: str, kind: str = "prop") -> dict:
    """Programmatic part of the KIT-STANDARD §4 checklist.

    prop:     square >=1024, sane filesize, near-white border ring (background,
              nothing crossing the frame edge), subject bbox inside margins,
              subject fill 62-95% of the frame.
    material: square >=1024, sane filesize (it is a full-bleed tile; the white
              background / subject-fill items do not apply by design).
    Returns verdict PASS | REVIEW | FAIL with reasons.
    """
    from PIL import Image

    res: dict = {"file": os.path.relpath(path, REPO), "kind": kind}
    try:
        im = Image.open(path)
        im.load()
    except Exception as exc:  # unreadable file
        res.update(verdict="FAIL", reasons=[f"unreadable: {exc}"])
        return res
    w, h = im.size
    fmt = im.format
    fsize = os.path.getsize(path)
    res.update(format=fmt, size=f"{w}x{h}", bytes=fsize,
               megapixels=round(w * h / 1e6, 2))
    reasons = []
    if fmt != "PNG":
        reasons.append(f"format {fmt} != PNG")
    if w != h or min(w, h) < 1024:
        reasons.append(f"not square >=1024 ({w}x{h})")
    if fsize < 60_000:
        reasons.append(f"file suspiciously small ({fsize} B)")
    if kind == "prop" and not reasons:
        rgb = im.convert("RGB")
        px = rgb.load()
        ring = 6
        border_total = border_white = 0
        edge_coords = [(x, yy) for x in range(w)
                       for yy in list(range(ring)) + list(range(h - ring, h))]
        edge_coords += [(x, y) for y in range(ring, h - ring)
                        for x in list(range(ring)) + list(range(w - ring, w))]
        for x, y in edge_coords:
            border_total += 1
            r, g, b = px[x, y]
            if min(r, g, b) >= 246:
                border_white += 1
        border_pct = 100.0 * border_white / max(border_total, 1)
        res["border_white_pct"] = round(border_pct, 2)
        if border_pct < 98.0:
            reasons.append(f"background not clean white at edges ({border_pct:.1f}% white)")
        # subject bbox = pixels meaningfully darker/coloured than white
        step = max(1, w // 512)
        minx, miny, maxx, maxy = w, h, -1, -1
        for y in range(0, h, step):
            for x in range(0, w, step):
                r, g, b = px[x, y]
                if (255 - min(r, g, b)) > 24 or (max(r, g, b) - min(r, g, b)) > 24:
                    if x < minx:
                        minx = x
                    if x > maxx:
                        maxx = x
                    if y < miny:
                        miny = y
                    if y > maxy:
                        maxy = y
        if maxx < 0:
            reasons.append("no subject pixels found")
        else:
            sub_w, sub_h = maxx - minx + 1, maxy - miny + 1
            fill = max(sub_w, sub_h) / w
            margins = {"left": minx, "top": miny, "right": w - 1 - maxx, "bottom": h - 1 - maxy}
            min_margin = min(margins.values())
            res.update(subject_bbox=[minx, miny, maxx, maxy],
                       subject_fill_pct=round(fill * 100, 1),
                       axis_fill_pct={"w": round(sub_w / w * 100, 1),
                                      "h": round(sub_h / h * 100, 1)},
                       margins_px=margins, min_margin_pct=round(min_margin / w * 100, 2))
            # Meshy hard rule: no part touching/extending beyond the boundary. The 70-90%
            # guidance is a detail-maximising heuristic; for tall thin props the long axis
            # legitimately reads tighter, so gate on the measured margin instead.
            if min_margin < 12:
                reasons.append(f"margin only {min_margin}px on one side (cropping risk)")
            if fill < 0.62:
                reasons.append(f"subject fills only {fill * 100:.0f}% of frame (<62%)")
    res["verdict"] = "FAIL" if [r for r in reasons if r.startswith(("format", "not square", "unreadable"))] else (
        "REVIEW" if reasons else "PASS")
    res["reasons"] = reasons
    return res


# ------------------------------------------------------------- backend: hermes

def _hermes_bootstrap():
    """Load the profile env and import the Hermes image provider. Returns provider or None."""
    if HERMES_SRC not in sys.path:
        sys.path.insert(0, HERMES_SRC)
    os.environ.setdefault("HERMES_HOME", HERMES_PROFILE_HOME)
    os.environ.setdefault("HERMES_PROFILE", os.path.basename(HERMES_PROFILE_HOME))
    env_file = os.path.join(HERMES_PROFILE_HOME, ".env")
    if os.path.exists(env_file):
        try:
            from dotenv import load_dotenv
            load_dotenv(env_file, override=False)
        except Exception:
            with open(env_file, encoding="utf-8", errors="ignore") as fh:
                for line in fh:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        k, _, v = line.partition("=")
                        os.environ.setdefault(k.strip(), v.strip())
    from plugins.image_gen.openai import OpenAIImageGenProvider  # type: ignore
    provider = OpenAIImageGenProvider()
    return provider if provider.is_available() else None


def _reexec_with_hermes_python() -> None:
    """Re-run this script under the Hermes venv python so provider imports work."""
    venv_py = os.path.join(HERMES_SRC, "venv", "bin", "python")
    if not os.path.exists(venv_py) or sys.executable == venv_py:
        print("backend hermes-tool unavailable: no Hermes venv python and imports failed",
              file=sys.stderr)
        sys.exit(3)
    env = dict(os.environ, HERMES_HOME=HERMES_PROFILE_HOME,
               HERMES_PROFILE=os.path.basename(HERMES_PROFILE_HOME))
    os.execve(venv_py, [venv_py, os.path.abspath(__file__), *sys.argv[1:]], env)


def ensure_hermes_python() -> None:
    """Provider calls must run under the Hermes venv python (openai sdk, dotenv)."""
    venv_py = os.path.join(HERMES_SRC, "venv", "bin", "python")
    if os.path.exists(venv_py) and os.path.realpath(sys.executable) != os.path.realpath(venv_py):
        _reexec_with_hermes_python()


# ------------------------------------------------------------------- ledger IO

def ledger_load() -> dict:
    return load_json(LEDGER)


def ledger_add(entry: dict) -> None:
    led = ledger_load()
    led["calls"].append(entry)
    led["total_attempts"] = len(led["calls"])
    led["delivered_images"] = len([
        c for c in led["calls"]
        if str(c.get("result", "")).startswith("ok") or ("file" in c and "result" not in c)
    ])
    save_json(LEDGER, led)


def cap_left() -> int:
    led = ledger_load()
    return int(led["cap"]) - len(led["calls"])


def next_n() -> int:
    return len(ledger_load()["calls"]) + 1


# --------------------------------------------------------------------- runner

def run_slot(arena: str, slot: str, role: str = "slot", provider=None,
             force: bool = False) -> dict:
    """Generate one image and install it. Returns the ledger entry dict."""
    p = pack(arena)
    spec = p["slots"][slot]
    target = delivered_path(arena, slot)
    n = next_n()
    entry: dict = {
        "n": n, "arena": arena, "slot": slot, "role": role,
        "ts": now(),
        "provider": "openai", "model": "gpt-image-2.5-flare",
        "aspect_ratio": "square", "kind": spec.get("kind", "prop"),
    }
    if spec.get("reference"):
        entry["reference"] = spec["reference"]
    if os.path.exists(target) and not force:
        entry["result"] = "skipped (already delivered)"
        journal(f"{arena}/{slot} SKIP already delivered")
        return entry  # no ledger append for skips
    if cap_left() <= 0:
        entry["result"] = "aborted: ledger cap reached"
        journal(f"n={n} {arena}/{slot} ABORT cap reached ({ledger_load()['cap']})")
        ledger_add(entry)
        return entry
    refs = []
    if spec.get("reference"):
        refs.append(os.path.join(REPO, spec["reference"]))
    try:
        result = provider.generate(
            prompt=spec["prompt"], aspect_ratio="square",
            reference_image_urls=refs or None)
    except Exception as exc:  # provider blew up — record and move on
        entry.update(result=f"failed: {type(exc).__name__}: {exc}")
        ledger_add(entry)
        journal(f"n={n} {arena}/{slot} FAIL {entry['result']}")
        return entry
    if not result.get("success"):
        entry.update(result=f"failed: {result.get('error_type')}: {result.get('error')}")
        ledger_add(entry)
        journal(f"n={n} {arena}/{slot} FAIL {entry['result']}")
        return entry
    cache = result.get("image")
    entry.update(result="ok", cache=os.path.basename(str(cache)))
    os.makedirs(os.path.dirname(target), exist_ok=True)
    if os.path.exists(target):
        rej = os.path.join(KITS, arena, "_rejected")
        os.makedirs(rej, exist_ok=True)
        keep = os.path.join(rej, f"{slot}-attempt{n}.png")
        shutil.copy2(target, keep)
        entry["archived_previous"] = os.path.relpath(keep, REPO)
    shutil.copy2(cache, target)
    chk = check_image(target, spec.get("kind", "prop"))
    entry["file"] = os.path.relpath(target, REPO)
    entry["size"] = chk.get("size")
    entry["sha256"] = sha256(target)
    entry["checklist"] = chk["verdict"]
    if chk.get("reasons"):
        entry["checklist_reasons"] = chk["reasons"]
    ledger_add(entry)
    journal(f"n={n} {arena}/{slot} OK {chk.get('size')} checklist={chk['verdict']} "
            f"{' | '.join(chk.get('reasons', []))}")
    return entry


def cmd_run(args) -> int:
    provider = None
    if args.backend in ("auto", "hermes-tool"):
        ensure_hermes_python()
        provider = _hermes_bootstrap()
        if provider is None and args.backend == "hermes-tool":
            print("hermes-tool backend unavailable", file=sys.stderr)
            return 3
    if provider is None:
        # jobs backend: emit payloads for the in-session image tool
        jobs = []
        for arena in ([args.arena] if args.arena else ARENAS):
            for slot in ([s for s in args.slots.split(",") if s] if args.slots else SLOTS):
                target = delivered_path(arena, slot)
                if os.path.exists(target):
                    continue
                spec = pack(arena)["slots"][slot]
                jobs.append({
                    "arena": arena, "slot": slot,
                    "prompt": spec["prompt"], "aspect_ratio": "square",
                    "reference_image_urls": ([os.path.join(REPO, spec["reference"])]
                                             if spec.get("reference") else []),
                    "install_cmd": (f"python3 tools/arena-kit/gen_assets.py --install <cache_path> "
                                    f"--arena {arena} --slot {slot}"),
                    "file": os.path.relpath(target, REPO),
                })
        os.makedirs(TMP, exist_ok=True)
        out = os.path.join(TMP, "jobs-pending.json")
        save_json(out, {"generated_at": now(), "jobs": jobs})
        print(f"backend jobs: wrote {len(jobs)} jobs to {os.path.relpath(out, REPO)}")
        return 0
    arenas = [args.arena] if args.arena else ARENAS
    slots = [s for s in args.slots.split(",") if s] if args.slots else SLOTS
    done = 0
    for arena in arenas:
        journal(f"--- arena {arena} start (cap left {cap_left()}) ---")
        for slot in slots:
            if args.limit and done >= args.limit:
                journal(f"--- limit {args.limit} reached; stopping ---")
                return 0
            entry = run_slot(arena, slot, provider=provider)
            if str(entry.get("result", "")).startswith(("ok", "failed", "aborted")):
                done += 1
            if str(entry.get("result", "")).startswith(("aborted",)):
                return 0
        journal(f"--- arena {arena} done (cap left {cap_left()}) ---")
    return 0


def cmd_regen(args) -> int:
    if (args.arena, args.slot) in PARENT_DELIVERED and not args.force_parent:
        print(f"refusing: {args.arena}/{args.slot} is parent-delivered (pass --force-parent "
              f"to override)", file=sys.stderr)
        return 2
    provider = ensure_hermes_python() or _hermes_bootstrap()
    if provider is None:
        print("hermes-tool backend unavailable", file=sys.stderr)
        return 3
    entry = run_slot(args.arena, args.slot, role="regen", provider=provider, force=True)
    print(json.dumps(entry, indent=1))
    return 0


def cmd_install(args) -> int:
    """Install an externally produced image (agent tool_call path) into the kit."""
    p = pack(args.arena)
    spec = p["slots"][args.slot]
    target = delivered_path(args.arena, args.slot)
    os.makedirs(os.path.dirname(target), exist_ok=True)
    shutil.copy2(args.cache, target)
    chk = check_image(target, spec.get("kind", "prop"))
    entry = {
        "n": next_n(), "arena": args.arena, "slot": args.slot, "role": args.role,
        "ts": now(), "provider": "openai", "model": "gpt-image-2.5-flare",
        "aspect_ratio": "square", "kind": spec.get("kind", "prop"),
        "cache": os.path.basename(args.cache), "result": "ok",
        "file": os.path.relpath(target, REPO), "size": chk.get("size"),
        "sha256": sha256(target), "checklist": chk["verdict"],
    }
    if chk.get("reasons"):
        entry["checklist_reasons"] = chk["reasons"]
    ledger_add(entry)
    journal(f"n={entry['n']} {args.arena}/{args.slot} OK(installed) {chk.get('size')} "
            f"checklist={chk['verdict']}")
    print(json.dumps(entry, indent=1))
    return 0


def cmd_verify(args) -> int:
    arenas = [args.arena] if args.arena else ARENAS
    rows, bad = [], 0
    for arena in arenas:
        p = pack(arena)
        for slot in SLOTS:
            target = delivered_path(arena, slot)
            if not os.path.exists(target):
                rows.append((arena, slot, "MISSING", ""))
                bad += 1
                continue
            chk = check_image(target, p["slots"][slot].get("kind", "prop"))
            if chk["verdict"] != "PASS":
                bad += 1
            rows.append((arena, slot, chk["verdict"],
                         f"{chk.get('size')} {chk.get('bytes', 0) // 1024}KB"
                         + (f" border={chk.get('border_white_pct')}%" if "border_white_pct" in chk else "")
                         + (f" fill={chk.get('subject_fill_pct')}%" if "subject_fill_pct" in chk else "")
                         + (f" minmargin={chk.get('min_margin_pct')}%" if "min_margin_pct" in chk else "")
                         + (f" {'; '.join(chk.get('reasons', []))}" if chk.get("reasons") else "")))
    width = max(len(f"{a}/{s}") for a, s, _, _ in rows)
    for arena, slot, verdict, detail in rows:
        print(f"{f'{arena}/{slot}'.ljust(width)}  {verdict.ljust(7)} {detail}")
    print(f"\n{len(rows)} files checked, {bad} not PASS")
    return 0


def cmd_sheet(args) -> int:
    from PIL import Image, ImageDraw

    arena = args.arena
    cells = []
    for slot in SLOTS:
        target = delivered_path(arena, slot)
        if os.path.exists(target):
            cells.append((slot, Image.open(target).convert("RGB").resize((512, 512))))
    cols = 4
    rows = (len(cells) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * 512, rows * 512), (230, 230, 230))
    draw = ImageDraw.Draw(sheet)
    for i, (slot, im) in enumerate(cells):
        x, y = (i % cols) * 512, (i // cols) * 512
        sheet.paste(im, (x, y))
        draw.rectangle([x, y, x + 511, y + 18], fill=(0, 0, 0))
        draw.text((x + 6, y + 4), f"{arena}/{slot}", fill=(255, 255, 255))
    os.makedirs(TMP, exist_ok=True)
    out = os.path.join(TMP, f"sheet-{arena}.png")
    sheet.save(out)
    print(out)
    return 0


def cmd_manifest(args) -> int:
    arena = args.arena
    p = pack(arena)
    target_dir = os.path.join(KITS, arena)
    os.makedirs(target_dir, exist_ok=True)
    lines = [
        f"# {arena} — arena kit image manifest",
        "",
        f"Pack: `tools/arena-kit/prompts/{arena}.json` · "
        f"concept still: `{p['concept_still']}` · "
        f"checklist: KIT-STANDARD §4 (6 gating items) · ledger: `art/arena-kits/image-spend.json`.",
        "",
        "| slot | object | view | file | checklist |",
        "|---|---|---|---|---|",
    ]
    for slot in SLOTS:
        spec = p["slots"][slot]
        target = delivered_path(arena, slot)
        if slot == "ground_texture":
            obj = "flat top-down tileable material swatch (NOT a Meshy prop)"
        else:
            obj = spec.get("subject", slot).replace("|", "/")
        view = spec["view"].replace("|", "/")
        if os.path.exists(target):
            chk = check_image(target, spec.get("kind", "prop"))
            flag = chk["verdict"]
            if chk.get("reasons"):
                flag += " (" + "; ".join(chk["reasons"]) + ")"
            if chk.get("subject_fill_pct") is not None:
                flag += (f" · fill {chk['subject_fill_pct']}% "
                         f"(min margin {chk.get('min_margin_pct')}%)")
        else:
            flag = "MISSING"
        lines.append(f"| `{slot}` | {obj} | {view} | `{os.path.relpath(target, REPO)}` | {flag} |")
    lines += [
        "",
        "Prompt template: `docs/mission/arena-kit/scan/image-prototyping.md` §6. The style "
        "block is byte-identical across every prompt in this pack (Meshy: wording drift is "
        "style drift). Ground texture is image-only — never upload it to Meshy; it is used "
        "as a material swatch.",
        "",
    ]
    out = os.path.join(target_dir, "MANIFEST.md")
    with open(out, "w") as fh:
        fh.write("\n".join(lines))
    print(out)
    return 0


def cmd_status(args) -> int:
    led = ledger_load()
    print(f"ledger cap {led['cap']} · attempts {len(led['calls'])} · left {cap_left()}")
    pending = []
    for arena in ARENAS:
        miss = [s for s in SLOTS if not os.path.exists(delivered_path(arena, s))]
        if miss:
            pending.append((arena, miss))
    for arena, miss in pending:
        print(f"  {arena}: {len(miss)} pending -> {', '.join(miss)}")
    if not pending:
        print("  all 55 delivered")
    return 0


def cmd_list(args) -> int:
    return cmd_status(args)


def cmd_set_cap(args) -> int:
    led = ledger_load()
    led["cap"] = args.set_cap
    led["cap_source"] = (led.get("cap_source", "") + " | " + args.cap_reason).strip(" |")
    save_json(LEDGER, led)
    print(f"cap set to {led['cap']} ({args.cap_reason})")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run", action="store_true")
    ap.add_argument("--regen", action="store_true")
    ap.add_argument("--install", metavar="CACHE")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--sheet", action="store_true")
    ap.add_argument("--manifest", action="store_true")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--set-cap", type=int, metavar="N")
    ap.add_argument("--cap-reason", default="")
    ap.add_argument("--arena", choices=ARENAS)
    ap.add_argument("--slot")
    ap.add_argument("--slots", default="")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--role", default="slot")
    ap.add_argument("--backend", choices=["auto", "hermes-tool", "jobs"], default="auto")
    ap.add_argument("--force-parent", action="store_true")
    args = ap.parse_args()

    if args.set_cap:
        return cmd_set_cap(args)
    if args.status or args.list:
        return cmd_status(args)
    if args.install:
        return cmd_install(args)
    if args.verify:
        return cmd_verify(args)
    if args.sheet:
        return cmd_sheet(args)
    if args.manifest:
        return cmd_manifest(args)
    if args.regen:
        return cmd_regen(args)
    if args.run:
        return cmd_run(args)
    ap.print_help()
    return 1


if __name__ == "__main__":
    # Re-exec under the Hermes venv python when the provider imports are missing
    try:
        import PIL  # noqa: F401
        sys.exit(main())
    except ImportError:
        _reexec_with_hermes_python()
