#!/usr/bin/env python3
"""gen_hud_labels.py — generate the `EVENT_LABELS` block of `godot/game/feedback_vocabulary.gd`.

WHY THIS EXISTS
---------------
The event log's vocabulary belongs to the one owner of the match's feedback
vocabulary, `godot/game/feedback_vocabulary.gd` (architecture-deepening gate 1;
the table used to live in `godot/game/hud.gd`, which now paints the log and asks
the module for the line). The owner's text comes from the verified locale layer
(`godot/src/locale/locale.gd` + `locale_data.gd`, the port of the frozen
`js/i18n.js`). One thing there is still a static table: `EVENT_LABELS`, the
message-id -> readable-line map that
`tools/i18n-port/hud-coverage.mjs --fail-on-leak` reads out of the module source
to decide whether a raw message id can reach the screen.

That probe models the resolution statically, so the table has to be complete for
every message id the ported simulation can emit. Hand-writing those 94 lines is
exactly the "second string table" defect the locale contract complains about
(`docs/wayfinder/evidence/i18n-port-contract.md` §8). So the lines are generated
from the verified locale data instead, and only the debt-ledger ids — the ten the
contract records as UNRESOLVABLE today, plus `serveHint`'s parameterless form —
carry a hand-written readable fallback.

The generator derives the id set from the same place the drift test does: the
emit sites of `godot/src/sim/**`, via `tools/i18n-port/emit-analysis.mjs`.
Nothing here re-implements the derivation: this script shells out to node.

USAGE
-----
    python3 godot/game/tools/gen_hud_labels.py            # rewrite the block in feedback_vocabulary.gd
    python3 godot/game/tools/gen_hud_labels.py --check    # exit 1 if feedback_vocabulary.gd differs

The generated block is delimited in feedback_vocabulary.gd by

    # >>> EVENT_LABELS (generated by godot/game/tools/gen_hud_labels.py) >>>
    ...
    # <<< EVENT_LABELS (generated ...) <<<

and everything outside those markers is hand-written.

WHY THE VALUES LOOK LIKE SOURCE TEXT
------------------------------------
`hud-coverage.mjs` matches `\t"key": "value",\n` and only compares strings, so a
generated block that differs in whitespace is a false alarm. The formatting below
is therefore fixed, and `--check` is a byte comparison.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
MODULE = REPO / "godot" / "game" / "feedback_vocabulary.gd"
LOCALE_DATA = REPO / "godot" / "src" / "locale" / "locale_data.gd"
LOCALE_RULES = REPO / "godot" / "src" / "locale" / "locale_rules.json"
BASELINE = REPO / "tools" / "i18n-port" / "unresolved-baseline.json"

BEGIN = "# >>> EVENT_LABELS (generated by godot/game/tools/gen_hud_labels.py) >>>"
END = "# <<< EVENT_LABELS (generated by godot/game/tools/gen_hud_labels.py) <<<"

## Readable fallbacks for the message ids the locale layer cannot turn into a
## sentence today (`tools/i18n-port/unresolved-baseline.json`, ten entries) plus
## `serveHint`, whose template needs two placeholders the simulation does not
## carry. Every value is DERIVED from the reference, never invented:
##
##   serveHint                 the reference's own template with its two
##                             placeholders dropped (`js/i18n.js`:
##                             "{ordinal} di servizio dal basso{suffix}: ...")
##   LET                       the reference's own `evLet` sentence (the id is
##                             `js/game.js:2135`'s hardcoded, untranslated
##                             "LET · Servizio da ripetere"; the literal form
##                             carries the id itself, which is the leak this
##                             table exists to prevent)
##   <reason> secondServe      `t(reason) + " " + t("secondServeSuffix")`
##                             (`js/game.js:2122-2124`)
##   doubleFault:<reason>      `t("doubleFault", {reason: t(<Reason>).lower()})`
##                             (`js/game.js:2128` — the reference lowercases the
##                             rendered sentence, which is why the fallback reads
##                             the way it does)
##   point<Side>:doubleFault:<reason>
##                             `t("pointYou"/"pointOpp") + " · " + <doubleFault>`
##                             (`js/game.js:2110`)
LEDGER_FALLBACKS = {
    "serveHint": "Servizio dal basso: cerca il diagonale.",
    "LET": "Let: nastro e rimbalzo nel riquadro corretto. Servizio da ripetere.",
    "serveOutBox secondServe": "Servizio fuori dal riquadro. Seconda di servizio.",
    "serveWallFault secondServe": "La palla ha colpito il vetro prima del rimbalzo Seconda di servizio.",
    "doubleFault:serveoutbox": "Doppio fallo: servizio fuori dal riquadro.",
    "doubleFault:servewallfault": "Doppio fallo: la palla ha colpito il vetro prima del rimbalzo",
    "pointYou:doubleFault:serveoutbox": "PUNTO TUO · Doppio fallo: servizio fuori dal riquadro.",
    "pointYou:doubleFault:servewallfault": "PUNTO TUO · Doppio fallo: la palla ha colpito il vetro prima del rimbalzo",
    "pointOpp:doubleFault:serveoutbox": "PUNTO AVVERSARIO · Doppio fallo: servizio fuori dal riquadro.",
    "pointOpp:doubleFault:servewallfault": "PUNTO AVVERSARIO · Doppio fallo: la palla ha colpito il vetro prima del rimbalzo",
}

## The node one-liner that derives the ids exactly as the drift test and the
## coverage probe do. It prints {"ids": [...], "categories": {...}}.
NODE_DERIVE = r"""
import { readFileSync } from "node:fs";
import { SIM_FILES, loadPortContext, collectEmitSites, deriveEmittedIds, classifyId } from "./tools/i18n-port/emit-analysis.mjs";
import { extractTables } from "./tools/i18n-port/extract-i18n.mjs";
const { rules, declarations, texts, frozen } = loadPortContext();
const files = [...new Set(SIM_FILES.concat((declarations.dynamicSites ?? []).filter((d) => !d.literalSite).map((d) => d.file)))];
const sites = collectEmitSites(files, (rel) => texts[rel]);
const extraction = extractTables(readFileSync("js/i18n.js", "utf8"));
const tables = { it: extraction.tables.it, en: extraction.tables.en, default: extraction.tables[rules.defaultLocale] };
const derived = deriveEmittedIds({ sites, declarations, texts, tables, frozen });
const out = {};
for (const id of derived.ids.keys()) out[id] = classifyId(id, tables, rules, extraction.fallbackLang).category;
process.stdout.write(JSON.stringify(out));
"""


def gdscript_table(path: Path) -> dict:
    """The `it` table of a generated locale_data.gd, as key -> value."""
    text = path.read_text(encoding="utf-8")
    at = text.index('"it": {')
    open_brace = text.index("{", at)
    depth = 0
    end = -1
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                end = i
                break
    body = text[open_brace + 1 : end]
    pairs = {}
    for key, value in re.findall(r'"([^"]+)":\s*"((?:[^"\\]|\\.)*)"', body):
        pairs[key] = value.replace('\\"', '"').replace("\\\\", "\\")
    return pairs


def emitted_ids() -> dict:
    result = subprocess.run(
        ["node", "--input-type=module", "-e", NODE_DERIVE],
        cwd=REPO, capture_output=True, text=True,
    )
    if result.returncode != 0:
        sys.exit("gen_hud_labels: node derivation failed:\n%s" % result.stderr)
    return json.loads(result.stdout)


def resolve(message_id: str, table: dict, rules: dict) -> str:
    """The `it` resolution of one id, with the rules of `locale_rules.json`.

    Mirrors `locale.gd::resolve`: split on the declared separator, bind by the
    declared rule, otherwise look the id up. The id itself is returned when the
    lookup fails — the caller decides what to do about that.
    """
    sep = rules.get("compositeSeparator", ":")
    if sep in message_id:
        parent, _, arg = message_id.partition(sep)
        rule = rules.get("compositeRules", {}).get(parent)
        if rule is not None:
            if rule["binding"] == "placeholder":
                return table.get(parent, parent).replace("{%s}" % rule["placeholder"], resolve(arg, table, rules))
            if rule["binding"] == "suffix":
                if arg == "":
                    return table.get(parent, parent)
                return table.get(parent, parent) + rule.get("separator", " · ") + resolve(arg, table, rules)
    return table.get(message_id, message_id)


def build_block() -> str:
    table = gdscript_table(LOCALE_DATA)
    rules = json.loads(LOCALE_RULES.read_text(encoding="utf-8"))
    categories = emitted_ids()
    lines = [BEGIN, "const EVENT_LABELS := {"]
    projected = []
    ledger = []
    for message_id in categories:
        if message_id in LEDGER_FALLBACKS:
            value = LEDGER_FALLBACKS[message_id]
            ledger.append(message_id)
        elif message_id.startswith(("pointYou:", "pointOpp:")) or message_id.startswith("doubleFault:") \
                or message_id.endswith(" secondServe"):
            # Resolvable composites: `hud-coverage.mjs` reproduces these forms
            # itself and any emitted id of this shape resolves through the locale
            # layer's declared composite rules, so an entry here would only be a
            # second copy of the same rule.
            continue
        else:
            value = resolve(message_id, table, rules)
            if value == message_id:
                sys.exit(
                    "gen_hud_labels: '%s' resolves to itself and has no ledger fallback "
                    "(category %s) — the ledger in tools/i18n-port/unresolved-baseline.json "
                    "and this file disagree." % (message_id, categories[message_id])
                )
            projected.append(message_id)
        if '"' in value or "{" in value or "}" in value:
            sys.exit("gen_hud_labels: value for '%s' cannot go into the table: %r" % (message_id, value))
        lines.append('\t"%s": "%s",' % (message_id, value))
    lines.append("}")
    lines.append(END)
    sys.stderr.write(
        "gen_hud_labels: %d entries — %d projected from the `it` table (%s), %d readable "
        "fallbacks from the debt ledger (%s)\n" % (
            len(projected) + len(ledger), len(projected), LOCALE_DATA.name, len(ledger),
            ", ".join(sorted(ledger)),
        )
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify feedback_vocabulary.gd instead of writing it")
    args = parser.parse_args()

    module = MODULE.read_text(encoding="utf-8")
    if BEGIN not in module or END not in module:
        sys.exit("gen_hud_labels: markers not found in %s" % MODULE.relative_to(REPO))
    head, _, rest = module.partition(BEGIN)
    _, _, tail = rest.partition(END)
    block = build_block()
    updated = head + block + tail

    if args.check:
        if updated == module:
            print("OK — feedback_vocabulary.gd EVENT_LABELS is byte-identical to the generated block")
            return 0
        print("DRIFT — feedback_vocabulary.gd EVENT_LABELS differs from the generated block")
        return 1
    MODULE.write_text(updated, encoding="utf-8")
    print("wrote %s (%d bytes)" % (MODULE.relative_to(REPO), len(updated.encode("utf-8"))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
