## drill_extras.gd — the exercises this port adds to the frozen reference's table.
##
## WHY THIS FILE EXISTS AT ALL, AND WHY IT IS NOT IN `modes.json`.
## `res://src/modes/data/modes.json::drill.exercises` is the frozen browser reference's
## own `DRILL_EXERCISES` (`js/drill.js:53-71`), generated by
## `tools/modes-port/extract-modes.mjs` and stamped with the sha256 of both source files.
## A fifth row typed into that document would make the port claim a reference it does not
## have, and the next regeneration would drop the row without saying so. So the extension
## lives HERE, in one Godot-only table, and `ModeTables.drill_catalog()` is the single
## place the two lists are joined. The frozen document is untouched, so its drift check
## still means exactly what it says, and `ModeTables.drill_exercises()` still answers the
## reference's own four rows for every audit that asks about them.
##
## `return` is the Jev coach's `serve_return` exercise (`docs/agent-work/jev-return/
## PLAN.md`): the OPPONENTS serve and the attempt is the human side's return. Its row
## carries the frozen table's own fields (`id`, `feed`, `rivals`, `targets`, `kinds`) plus
## the two it needs to describe itself truthfully:
##
##   `opponentServe` — who puts the ball in play. `drill_session.gd` reads it instead of
##     guessing from the id, so a second serving exercise cannot land on the wrong side.
##   `godotOnly` — a marker for anything that wants to tell the reference's rows from this
##     one (the audits do).
##
## NOTHING HERE SIMULATES ANYTHING. The row is data: the engine, the drill session and the
## scoring module do all the work exactly as they do for the frozen four.
extends RefCounted

## The one exercise this build adds. The id is the coach's own advice target
## (`godot/src/coach/coach_advice.gd`: `serve_return` -> `return`).
const RETURN_ID := "return"

const RETURN_EXERCISE := {
	"id": RETURN_ID,
	"feed": "serve",
	"opponentServe": true,
	"rivals": true,
	"targets": false,
	"kinds": [],
	"godotOnly": true,
}


## Every Godot-only exercise, in the order they are appended after the frozen ones. A copy
## per call, so a caller that mutates a row cannot corrupt the table for the next one.
static func exercises() -> Array:
	return [RETURN_EXERCISE.duplicate(true)]


## True when this id is one of the Godot-only rows rather than a reference one.
static func is_extra(exercise_id: String) -> bool:
	for row in exercises():
		if String((row as Dictionary).get("id", "")) == exercise_id:
			return true
	return false


## The exercise's own ids, the frozen list's first.
static func ids() -> Array[String]:
	var out: Array[String] = []
	for row in exercises():
		out.append(String((row as Dictionary).get("id", "")))
	return out
